name: magisk-root-sprd-ums312-local-apk
on:
  workflow_dispatch:
    inputs:
      IMG_URL:
        description: '原厂 boot.img 直链'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: 从本地Magisk-v23.0.apk提取magiskboot + 修补 + 展讯签名
      run: |
        sudo apt update
        sudo apt -y install build-essential openssl curl wget busybox unzip

        mkdir work
        git clone https://github.com/TomKing062/vendor_sprd_proprietories-source_packimage.git
        cp -a vendor_sprd_proprietories-source_packimage/sign_image/config-unisoc work/
        cp vendor_sprd_proprietories-source_packimage/sign_image/v2/sign_image_v1.sh work/
        gcc -o work/get-raw-image vendor_sprd_proprietories-source_packimage/sign_image/get-raw-image.c

        cd vendor_sprd_proprietories-source_packimage/sign_image/v2/insertheader && make
        cd ../sprd_sign && make
        cd ../../../../

        cp vendor_sprd_proprietories-source_packimage/sign_image/v2/insertheader/imgheaderinsert work/
        cp vendor_sprd_proprietories-source_packimage/sign_image/v2/sprd_sign/sprd_sign work/
        chmod +x work/*
        cd work

        # 下载你的 boot
        curl -o boot_original.img -L "${{ github.event.inputs.IMG_URL }}"

        # ==============================================
        # 关键：从你仓库里的 Magisk-v23.0.apk 本地提取
        # ==============================================
        unzip -j ../Magisk-v23.0.apk "lib/arm64-v8a/libmagiskboot.so" -d .
        mv libmagiskboot.so magiskboot
        chmod +x magiskboot

        # 修补 ROOT
        ./magiskboot unpack boot_original.img
        ./magiskboot patch
        ./magiskboot repack boot_original.img boot_magisk.img
        ./magiskboot cleanup

        # 展讯格式处理
        mv boot_magisk.img boot.bin
        ./get-raw-image boot.bin
        truncate -s 35M boot.raw

        # 签名
        ./sign_image_v1.sh

        cp boot-sign.bin ../magisk-root-signed-boot.img

    - name: 上传成品
      uses: softprops/action-gh-release@v1
      with:
        files: magisk-root-signed-boot.img
        name: UMS312-Magisk-Root-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          设备：HLTE217T / UMS312
          Android 9
          Magisk：v23.0（本地仓库提取）
          状态：已ROOT + 已签名 + 35M裁剪
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
